import {CONFIG} from "./config.js";
import {taskDefinitions,folderDefinitions,taskHints} from "./data.js";
import {getSession,signIn,signOut,listOrders,createOrder,updateCompensation,getDocumentUrl,uploadTaskDocument,completeTask,reopenTask,MAX_FILE_BYTES} from "./supabase_api.js";

const app=document.querySelector("#app");let orders=[],selectedId=null,view="dashboard",session=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]));
const bal=o=>({ship:Math.max(0,(+o.qtyRequested||0)-(+o.qtyShipped||0)),invoice:Math.max(0,(+o.qtyRequested||0)-(+o.qtyInvoiced||0))});
const taskProgress=o=>{const ts=o.tasks||[];return ts.length?Math.round(ts.filter(x=>x.status==="Completed").length/ts.length*100):0};
const stat=o=>taskProgress(o)===100?"Completed":taskProgress(o)>0?"In Progress":"Not Started";
const pill=s=>`<span class="pill ${String(s).toLowerCase().replaceAll(" ","-")}">${esc(s)}</span>`;
const nav=(id,t,i)=>`<button class="nav ${view===id?"active":""}" data-nav="${id}"><span>${i}</span>${t}</button>`;
const fmtKB=b=>`${(Number(b||0)/1024).toFixed(1)} KB`;

async function boot(){if(CONFIG.DEMO_MODE){showLogin("Demo mode is disabled. Connect the portal to Supabase.");return;}try{session=await getSession();}catch(e){showError(e.message);return;}if(!session){showLogin();return;}await refresh();}
async function refresh(){try{orders=await listOrders();selectedId=selectedId&&orders.some(o=>o.id===selectedId)?selectedId:(orders[0]?.id||null);render();}catch(e){showError(e.message);}}
function showError(msg){app.innerHTML=`<div class="fatal"><div class="fatal-card"><b>GUVEL / CONNECTION</b><h2>Supabase connection error</h2><p>${esc(msg)}</p><small>Check config.js, Supabase SQL/RLS and Authentication.</small></div></div>`;}
function showLogin(message=""){app.innerHTML=`<div class="guvel-login"><div class="login-grid"><div class="login-copy"><div class="login-brand"><span class="gmark">G</span><div><strong>GUVEL</strong><small>SMARTER QUALITY SOLUTIONS</small></div></div><div class="orb"></div><span class="eyebrow">QUALITY CONTROL / PREPPAP</span><h1>PrePPAP<br><span>Command Center</span></h1><p>Control documental, trazabilidad y cierre de evidencia en un solo flujo.</p><div class="login-stats"><span><b>50 KB</b> Max. evidence</span><span><b>09</b> Workflow gates</span><span><b>100%</b> Traceability</span></div></div><div class="login-card"><small>SECURE WORKSPACE</small><h2>Sign in</h2><p>Access is managed through Supabase Authentication.</p><form id="loginForm"><label>Email<input name="email" type="email" autocomplete="username" placeholder="you@company.com" required></label><label>Password<input name="password" type="password" autocomplete="current-password" placeholder="••••••••" required></label><button class="primary login-submit">Enter workspace <span>→</span></button></form><div id="loginMsg" class="login-msg">${esc(message)}</div></div></div><div class="login-footer">GUVEL PREPPAP · EVIDENCE FIRST · SECURE WORKSPACE</div></div>`;
document.querySelector("#loginForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),msg=document.querySelector("#loginMsg"),btn=document.querySelector(".login-submit");btn.disabled=true;btn.innerHTML="Authenticating…";try{await signIn(f.get("email"),f.get("password"));session=await getSession();if(!session)throw new Error("Supabase did not return an active session.");await refresh();}catch(err){let m=err.message||"Unable to sign in.";if(/email not confirmed/i.test(m))m="Email not confirmed. Confirm the user in Supabase Authentication → Users.";if(/invalid login credentials/i.test(m))m="Invalid email or password.";msg.className="login-msg error-msg";msg.textContent=m;btn.disabled=false;btn.innerHTML="Enter workspace <span>→</span>";}};}
function render(){app.innerHTML=`<div class="shell"><aside><div class="brand"><b>G</b><div><strong>GUVEL</strong><small>PREPPAP // CTRL</small></div></div><div class="side-label">WORKSPACE</div><nav>${nav("dashboard","Command Center","◈")}${nav("orders","PrePPAP Orders","▣")}${nav("tasks","Evidence Flow","✓")}${nav("balances","PO Balance","↔")}${nav("shipments","Shipments","⌁")}</nav><div class="side-status"><span class="live-dot"></span><div><b>SUPABASE ONLINE</b><small>Authenticated session</small></div></div><div class="sidefoot"><button id="auth">Sign out</button><small>GUVEL SYSTEMS · v2</small></div></aside><main><header><div><small>GUVEL SYSTEMS / PREPPAP CONTROL</small><h1>${({dashboard:"Command Center",orders:"PrePPAP Orders",tasks:"Evidence Flow",balances:"PO Balance",shipments:"Shipment Control"})[view]}</h1></div><div class="actions"><span class="connection"><i></i>LIVE</span><button class="primary" id="new">+ New PrePPAP</button></div></header><section class="content">${content()}</section></main></div>`;bind();}
function content(){if(view==="dashboard")return dashboard();if(view==="orders")return ordersPage();if(view==="tasks")return tasksPage();if(view==="balances")return balancesPage();return shipmentsPage();}
function dashboard(){const completed=orders.filter(o=>stat(o)==="Completed").length,open=orders.reduce((s,o)=>s+bal(o).ship,0),evidence=orders.reduce((s,o)=>s+(o.documents||[]).length,0),avg=orders.length?Math.round(orders.reduce((s,o)=>s+taskProgress(o),0)/orders.length):0;return `<div class="hero"><div><span class="eyebrow">PREPPAP DIGITAL CONTROL</span><h2>Evidence-driven workflow.</h2><p>Every stage requires documented evidence before it can be closed.</p></div><div class="hero-ring" style="--p:${avg*3.6}deg"><span>${avg}%<small>AVG FLOW</small></span></div></div><div class="metrics"><div class="metric"><small>ACTIVE ORDERS</small><strong>${orders.length}</strong><em>Tracked PrePPAPs</em></div><div class="metric"><small>COMPLETED</small><strong>${completed}</strong><em>All gates closed</em></div><div class="metric"><small>OPEN QUANTITY</small><strong>${open}</strong><em>Pieces pending</em></div><div class="metric"><small>EVIDENCE FILES</small><strong>${evidence}</strong><em>≤ 50 KB each</em></div></div><div class="twocol"><section class="panel glow"><div class="head"><div><h2>Active PrePPAP Signals</h2><p>Select an order to open its evidence workflow.</p></div><button class="link" data-nav="orders">View all →</button></div>${orders.slice(0,6).map(row).join("")||`<div class="empty">No PrePPAP orders yet. Create your first order.</div>`}</section><section class="panel"><div class="head"><div><h2>Control Matrix</h2><p>System-enforced operating logic</p></div></div>${[["01","Evidence required","A task cannot close without a file."],["02","50 KB hard limit","Applies to every uploaded file."],["03","Traceable gate","Each file is linked to its workflow step."],["04","PO balance","Partial quantities remain visible until resolved."]].map(x=>`<div class="rule"><b>${x[0]}</b><div><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join("")}</section></div>`;}
function row(o){const p=taskProgress(o),b=bal(o);return `<button class="orderrow" data-order="${esc(o.id)}"><div><b>${esc(o.id)}</b><span>${esc(o.customer)} · ${esc(o.partNumber)}</span></div><div class="row-progress"><span><i style="width:${p}%"></i></span><small>${p}% evidence</small></div><div>${pill(stat(o))}</div></button>`;}
function ordersPage(){return `<div class="toolbar"><input id="search" placeholder="Search PrePPAP, customer, part number..."><select id="filter"><option>All Status</option><option>Completed</option><option>In Progress</option><option>Not Started</option></select></div><section class="panel table"><table><thead><tr><th>PrePPAP</th><th>Customer</th><th>Part</th><th>Purpose</th><th>Evidence</th><th>Open Qty</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table></section>${selectedId?detail(orders.find(x=>x.id===selectedId)):``}`;}
function fill(){const body=document.querySelector("#rows");if(!body)return;const s=document.querySelector("#search")?.value||"",f=document.querySelector("#filter")?.value||"All Status";body.innerHTML=orders.filter(o=>[o.id,o.customer,o.partNumber,o.purpose].join(" ").toLowerCase().includes(s.toLowerCase())&&(f==="All Status"||stat(o)===f)).map(o=>`<tr data-order="${esc(o.id)}"><td><b>${esc(o.id)}</b></td><td>${esc(o.customer)}</td><td>${esc(o.partNumber)}</td><td>${esc(o.purpose)}</td><td><div class="table-progress"><i style="width:${taskProgress(o)}%"></i></div><small>${taskProgress(o)}%</small></td><td class="${bal(o).ship?"red":""}">${bal(o).ship}</td><td>${pill(stat(o))}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">No orders found.</td></tr>`;}
function detail(o){if(!o)return "";const b=bal(o),p=taskProgress(o);return `<section class="panel detail glow"><div class="detailhead"><div><span class="eyebrow">${esc(o.id)}</span><h2>${esc(o.customer)} <span>·</span> ${esc(o.partNumber)}</h2><p>${esc(o.purpose)} · Required ${esc(o.requiredDate||"—")}</p></div><div class="detail-score"><b>${p}%</b><small>FLOW</small></div></div><div class="qtygrid"><div><small>REQUESTED</small><b>${o.qtyRequested} pcs</b></div><div><small>SHIPPED</small><b>${o.qtyShipped} pcs</b></div><div class="${b.ship?"warn":""}"><small>REMAINING SHIP</small><b>${b.ship} pcs</b></div><div class="${b.invoice?"warn":""}"><small>REMAINING INVOICE</small><b>${b.invoice} pcs</b></div></div><div class="workflow"><div class="workflow-head"><div><h3>PrePPAP Evidence Flow</h3><p>Open any gate to upload evidence and complete it.</p></div><span class="file-rule">MAX FILE · 50 KB</span></div>${taskDefinitions.map((t,i)=>{const task=o.tasks?.find(x=>x.task_code===t[0]);const docs=o.documents?.filter(d=>d.task_code===folderFor(t[0]))||[];return `<button class="gate ${task?.status==="Completed"?"done":""}" data-task="${esc(t[0])}"><span class="gate-no">${String(i+1).padStart(2,"0")}</span><span class="gate-icon">${task?.status==="Completed"?"✓":"+"}</span><span class="gate-copy"><b>${esc(t[1])}</b><small>${esc(t[2])} → ${esc(t[3])}</small></span><span class="gate-evidence">${docs.length} file${docs.length===1?"":"s"}</span><span class="gate-status">${pill(task?.status||"Not Started")}</span><span>→</span></button>`}).join("")}</div>${b.ship?`<div class="alert"><b>⚠ ${b.ship} pc pending.</b> Open PO Balance to define the compensation action.</div>`:""}</section>`;}
function folderFor(code){return folderDefinitions.find(x=>x[0]===code)?.[1]||code;}
function tasksPage(){return `<section class="panel table"><table><thead><tr><th>PrePPAP</th><th>Gate</th><th>Evidence</th><th>Due</th><th>Status</th></tr></thead><tbody>${orders.flatMap(o=>(o.tasks||[]).map(t=>`<tr><td><b>${esc(o.id)}</b></td><td>${esc(t.task_name)}</td><td>${o.documents.filter(d=>d.task_code===folderFor(t.task_code)).length}</td><td>${esc(t.due_date||"—")}</td><td>${pill(t.status)}</td></tr>`)).join("")||`<tr><td colspan="5" class="empty">No tasks.</td></tr>`}</tbody></table></section>`;}
function balancesPage(){return `<div class="balancebar"><div><h2>PO Balance & Compensation</h2><p>Every quantity mismatch must have an explicit disposition.</p></div><button class="primary" id="addBalance">+ Add Compensation</button></div><section class="panel table"><table><thead><tr><th>PrePPAP</th><th>PO</th><th>Ordered</th><th>Delivered</th><th>Remaining</th><th>Action</th><th>Related PO</th><th>Resolution</th><th>Status</th><th></th></tr></thead><tbody>${orders.flatMap(o=>(o.balances||[]).map((x,i)=>`<tr><td><b>${esc(o.id)}</b></td><td>${esc(x.po_number)}</td><td>${x.ordered_qty}</td><td>${x.delivered_qty}</td><td class="red"><b>${Math.max(0,x.ordered_qty-x.delivered_qty)}</b></td><td>${esc(x.action||"—")}</td><td>${esc(x.related_po||"—")}</td><td>${esc(x.resolution_date||"—")}</td><td>${pill(x.status||"Open")}</td><td><button class="mini" data-edit-balance="${esc(o.id)}" data-bi="${i}">Edit</button></td></tr>`)).join("")||`<tr><td colspan="10" class="empty">No compensation records.</td></tr>`}</tbody></table></section>`;}
function shipmentsPage(){return `<section class="panel table"><table><thead><tr><th>PrePPAP</th><th>Method</th><th>Part</th><th>Purpose</th><th>Qty</th><th>FedEx</th><th>References</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${esc(o.id)}</b></td><td>${esc(o.shippingMethod||"")}</td><td>${esc(o.partNumber)}</td><td>${esc(o.purpose)}</td><td>${o.qtyShipped}</td><td>${esc(o.fedex||"—")}</td><td>${o.shippingMethod==="MWS → Customer"?esc(o.partNumber)+" · "+esc(o.purpose):"MES process"}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">No shipments.</td></tr>`}</tbody></table></section>`;}

function modal(html){document.body.insertAdjacentHTML("beforeend",`<div class="modalbg" id="modal"><div class="modal">${html}</div></div>`);document.querySelectorAll("#modal .close").forEach(x=>x.addEventListener("click",()=>document.querySelector("#modal").remove()));}
function taskModal(order,taskCode){
 const task=order.tasks.find(x=>x.task_code===taskCode),hint=taskHints[taskCode]||{},folder=folderFor(taskCode),docs=order.documents.filter(x=>x.task_code===folder);
 modal(`<div class="modalhead neon"><div><span class="eyebrow">GATE ${String(taskDefinitions.findIndex(x=>x[0]===taskCode)+1).padStart(2,"0")}</span><h2>${esc(hint.label||task.task_name)}</h2><p>${esc(task.from_party)} → ${esc(task.to_party)}</p></div><button class="close">×</button></div><div class="gate-modal"><div class="requirement"><span>01</span><div><b>Evidence required</b><small>No se puede marcar como completado sin al menos un archivo.</small></div></div><div class="upload-zone" id="dropZone"><input id="taskFile" type="file" hidden><div class="upload-symbol">↑</div><b>Upload evidence</b><small>Máximo 50 KB · aplica a todos los archivos</small><button type="button" class="secondary" id="chooseFile">Select file</button><div id="fileName"></div></div><div class="file-list">${docs.map(d=>`<button class="doc" data-doc="${esc(d.storage_path)}"><span>▣</span><div><b>${esc(d.document_name)}</b><small>${fmtKB(d.size_bytes)} · ${new Date(d.created_at).toLocaleString()}</small></div><em>↗</em></button>`).join("")||`<div class="empty">No evidence uploaded yet.</div>`}</div><div class="task-info"><label>${esc(hint.reference||"Reference")}<input id="taskReference" value="${esc(task.reference||"")}" placeholder="Reference / number"></label><label>Information / notes<textarea id="taskDetails" placeholder="Relevant information...">${esc(task.details||"")}</textarea></label></div></div><div class="modalactions"><button type="button" class="secondary close">Close</button>${task.status==="Completed"?`<button class="secondary" id="reopenTask">Reopen gate</button>`:`<button class="primary" id="completeTask" ${docs.length?"":"disabled"}>Complete gate ✓</button>`}</div></div>`);
 const input=document.querySelector("#taskFile"),choose=document.querySelector("#chooseFile"),name=document.querySelector("#fileName"),complete=document.querySelector("#completeTask");
 choose.onclick=()=>input.click();
 input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>MAX_FILE_BYTES){alert(`Máximo 50 KB. Tu archivo pesa ${fmtKB(f.size)}.`);input.value="";return;}try{await uploadTaskDocument(order.dbId,folder,f,order.folderPath);document.querySelector("#modal").remove();await refresh();const fresh=orders.find(x=>x.id===order.id);taskModal(fresh,taskCode);}catch(e){alert(e.message);}};
 complete?.addEventListener("click",async()=>{try{await completeTask(task.id,order.dbId,folder,{reference:document.querySelector("#taskReference").value,details:document.querySelector("#taskDetails").value});document.querySelector("#modal").remove();await refresh();view="orders";render();}catch(e){alert(e.message);}});
 document.querySelector("#reopenTask")?.addEventListener("click",async()=>{try{await reopenTask(task.id);document.querySelector("#modal").remove();await refresh();view="orders";render();}catch(e){alert(e.message);}});
 document.querySelectorAll("#modal [data-doc]").forEach(x=>x.onclick=async()=>{try{window.open(await getDocumentUrl(x.dataset.doc),"_blank");}catch(e){alert(e.message);}});
}
function newOrder(){modal(`<div class="modalhead neon"><div><span class="eyebrow">NEW PREPPAP</span><h2>Create PrePPAP Order</h2><p>Build the control record first. Evidence is captured at each gate.</p></div><button class="close">×</button></div><form id="orderForm"><div class="formgrid"><label>Customer<input name="customer" required></label><label>Part Number<input name="partNumber" required></label><label>Revision<input name="revision"></label><label>Purpose<select name="purpose"><option>Prototype</option><option>Validation</option><option>Pre-Production</option><option>PPAP</option><option>Sample</option><option>Other</option></select></label><label>Request Date<input name="requestDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Required Date<input name="requiredDate" type="date"></label><label>Qty Requested<input name="qtyRequested" type="number" min="0" required></label><label>Priority<select name="priority"><option>Normal</option><option>Low</option><option>High</option><option>Critical</option></select></label><label>Owner<select name="owner"><option>Quality</option><option>Engineering</option><option>Purchasing</option><option>Logistics</option><option>Finance</option><option>MES</option><option>MWS</option></select></label><label>Shipping Method<select name="shippingMethod"><option>Monterrey → Customer</option><option>MWS → Customer</option></select></label><label>Customer PO #<input name="customerPO"></label><label>Customer PO Qty<input name="customerPOQty" type="number" min="0"></label><label>PrePPAP Request #<input name="prePPAPRequest"></label><label>MES PO #<input name="mesPO"></label><label>MES PO Qty<input name="mesPOQty" type="number" min="0"></label><label>MWS Invoice #<input name="mwsInvoice"></label><label>MWS Invoice Qty<input name="mwsInvoiceQty" type="number" min="0"></label><label>FedEx / Tracking<input name="fedex"></label><label>Qty Shipped<input name="qtyShipped" type="number" min="0" value="0"></label><label>Qty Invoiced<input name="qtyInvoiced" type="number" min="0" value="0"></label><label class="full">Comments<textarea name="comments"></textarea></label></div><div class="modalactions"><button type="button" class="secondary close">Cancel</button><button class="primary">Create Order</button></div></form></div>`);
 document.querySelector("#orderForm").onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await createOrder(f);document.querySelector("#modal").remove();view="orders";await refresh();render();}catch(err){alert(err.message);}};
}
function balanceModal(order,idx=-1){const x=idx>=0?order.balances[idx]:{po_type:"MES PO to MWS",po_number:order.mesPO||"",ordered_qty:order.mesPOQty||0,delivered_qty:order.qtyShipped||0,action:"",related_po:"",resolution_date:"",status:"Open",comments:""};modal(`<div class="modalhead neon"><div><span class="eyebrow">${esc(order.id)}</span><h2>${idx>=0?"Edit":"Add"} Compensation</h2></div><button class="close">×</button></div><form id="balanceForm"><div class="formgrid"><label>PO Type<select name="po_type"><option>MES PO to MWS</option><option>Customer PO to MES</option><option>Other</option></select></label><label>PO Number<input name="po_number" value="${esc(x.po_number)}"></label><label>Ordered Qty<input name="ordered_qty" type="number" min="0" value="${x.ordered_qty}" required></label><label>Delivered / Shipped Qty<input name="delivered_qty" type="number" min="0" value="${x.delivered_qty}" required></label><label class="full">Compensation Action<select name="action"><option value="">Select action</option><option>Ship with next PrePPAP order</option><option>Ship separately</option><option>Credit</option><option>Cancel</option><option>Transfer to another PO</option></select></label><label>Related PO<input name="related_po" value="${esc(x.related_po)}"></label><label>Resolution Date<input name="resolution_date" type="date" value="${esc(x.resolution_date)}"></label><label>Status<select name="status"><option>Open</option><option>Partial</option><option>Closed</option></select></label><label class="full">Comments<textarea name="comments">${esc(x.comments)}</textarea></label></div><div class="balancepreview">Remaining quantity: <strong id="remainingPreview">${Math.max(0,(x.ordered_qty||0)-(x.delivered_qty||0))} pcs</strong></div><div class="modalactions"><button type="button" class="secondary close">Cancel</button><button class="primary">Save Compensation</button></div></form></div>`);const form=document.querySelector("#balanceForm"),update=()=>document.querySelector("#remainingPreview").textContent=Math.max(0,(+form.ordered_qty.value||0)-(+form.delivered_qty.value||0))+" pcs";form.ordered_qty.oninput=update;form.delivered_qty.oninput=update;form.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(form));f.ordered_qty=+f.ordered_qty;f.delivered_qty=+f.delivered_qty;if(f.ordered_qty===f.delivered_qty)f.status="Closed";try{await updateCompensation(order.dbId,idx,f,idx>=0?order.balances[idx].id:null);document.querySelector("#modal").remove();await refresh();view="balances";render();}catch(err){alert(err.message);}};}
function bind(){document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>{view=x.dataset.nav;render();});document.querySelectorAll("[data-order]").forEach(x=>x.onclick=()=>{selectedId=x.dataset.order;view="orders";render();});document.querySelector("#new")?.addEventListener("click",newOrder);document.querySelector("#auth")?.addEventListener("click",async()=>{await signOut();session=null;showLogin();});document.querySelector("#search")?.addEventListener("input",fill);document.querySelector("#filter")?.addEventListener("change",fill);fill();document.querySelector("#addBalance")?.addEventListener("click",()=>{const o=orders.find(x=>x.id===selectedId)||orders[0];if(o)balanceModal(o);});document.querySelectorAll("[data-edit-balance]").forEach(x=>x.onclick=()=>{const o=orders.find(a=>a.id===x.dataset.editBalance);balanceModal(o,+x.dataset.bi);});document.querySelectorAll("[data-task]").forEach(x=>x.onclick=()=>{const o=orders.find(a=>a.id===selectedId);if(o)taskModal(o,x.dataset.task);});document.querySelectorAll("[data-doc]").forEach(x=>x.onclick=async()=>{try{window.open(await getDocumentUrl(x.dataset.doc),"_blank");}catch(e){alert(e.message);}});}
boot();
