import{CONFIG}from"./config.js";import{demoOrders,taskDefinitions}from"./data.js";import{loadLocalOrders,saveLocalOrders}from"./storage.js";import{SharePointAdapter}from"./sharepoint.js";
let orders=loadLocalOrders(demoOrders),view="dashboard",selected=orders[0]?.id||null;const app=document.querySelector("#app");let msalInstance=null,adapter=null;
const esc=x=>String(x??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]));const bal=o=>({ship:Math.max(0,(o.qtyRequested||0)-(o.qtyShipped||0)),invoice:Math.max(0,(o.qtyRequested||0)-(o.qtyInvoiced||0))});const stat=o=>{const b=bal(o);return b.ship===0&&b.invoice===0?"Completed":(o.qtyShipped||o.qtyInvoiced)?"In Progress":"Not Started"};const pill=s=>`<span class="pill ${s.toLowerCase().replaceAll(" ","-")}">${s}</span>`;
function render(){app.innerHTML=`<div class="shell"><aside><div class="brand"><b>G</b><div><strong>GUVEL</strong><small>PrePPAP</small></div></div><nav>${nav("dashboard","▦","Dashboard")}${nav("orders","◫","PrePPAP Orders")}${nav("tasks","✓","Tasks")}${nav("balances","↔","PO Balance")}${nav("shipments","⌁","Shipments")}</nav><div class="mode">${CONFIG.DEMO_MODE?"DEMO MODE":"SHAREPOINT MODE"}</div></aside><main><header><div><small>GUVEL SYSTEMS</small><h1>${({dashboard:"PrePPAP Control",orders:"PrePPAP Orders",tasks:"Task Tracker",balances:"PO Balance & Compensation",shipments:"Shipment Control"})[view]}</h1></div><div class="actions"><span class="connection">● ${CONFIG.DEMO_MODE?"Local demo":"SharePoint"}</span><button id="new">+ New PrePPAP</button></div></header><section>${content()}</section></main></div>`;bind()}
function nav(id,ic,t){return`<button class="nav ${view===id?"active":""}" data-nav="${id}">${ic} ${t}</button>`}
function content(){if(view==="dashboard")return dashboard();if(view==="orders")return ordersView();if(view==="tasks")return tasksView();if(view==="balances")return balances();return shipments()}
function dashboard(){let c=orders.filter(o=>stat(o)==="Completed").length,oq=orders.reduce((s,o)=>s+bal(o).ship,0),iq=orders.reduce((s,o)=>s+bal(o).invoice,0);return`<div class="metrics"><div><small>Total Orders</small><b>${orders.length}</b><span>All PrePPAP orders</span></div><div><small>Completed</small><b>${c}</b><span>No quantity balance</span></div><div><small>Open Ship Qty</small><b>${oq}</b><span>Pieces remaining</span></div><div><small>Open Invoice Qty</small><b>${iq}</b><span>Pieces not invoiced</span></div></div><div class="cols"><div class="panel"><div class="head"><h2>Active Orders</h2><button data-nav="orders">View all →</button></div>${orders.map(row).join("")}</div><div class="panel rules"><div class="head"><h2>Control Rules</h2></div><p><b>01</b> Unique PrePPAP ID + folder per order.</p><p><b>02</b> Partial POs create explicit remaining quantity.</p><p><b>03</b> An order cannot be complete while quantity remains.</p><p><b>04</b> MWS → Customer requires FedEx + Part Number + Purpose.</p></div></div>`}
function row(o){let b=bal(o);return`<button class="row" data-order="${o.id}"><div><b>${esc(o.id)}</b><small>${esc(o.customer)} · ${esc(o.partNumber)}</small></div><span>${o.qtyRequested} pcs ${b.ship?`· ${b.ship} open`:""}</span>${pill(stat(o))}</button>`}
function ordersView(){return`<div class="toolbar"><input id="q" placeholder="Search PrePPAP, customer, part number..."><select id="f"><option>All Status</option><option>Completed</option><option>In Progress</option><option>Not Started</option></select></div><div class="panel table"><table><thead><tr><th>PrePPAP</th><th>Customer</th><th>Part Number</th><th>Purpose</th><th>Qty</th><th>Open</th><th>Shipping</th><th>Status</th></tr></thead><tbody id="tbody"></tbody></table></div>${detail(orders.find(o=>o.id===selected))}`}
function populate(){const q=document.querySelector("#q")?.value.toLowerCase()||"",f=document.querySelector("#f")?.value||"All Status",body=document.querySelector("#tbody");if(!body)return;body.innerHTML=orders.filter(o=>(o.id+o.customer+o.partNumber+o.purpose).toLowerCase().includes(q)&&(f==="All Status"||stat(o)===f)).map(o=>{let b=bal(o);return`<tr data-order="${o.id}"><td><b>${o.id}</b></td><td>${esc(o.customer)}</td><td>${esc(o.partNumber)}</td><td>${esc(o.purpose)}</td><td>${o.qtyRequested}</td><td class="${b.ship?"balance":""}">${b.ship}</td><td>${esc(o.shippingMethod)}</td><td>${pill(stat(o))}</td></tr>`}).join("")||`<tr><td colspan="8" class="empty">No orders found.</td></tr>`}
function detail(o){if(!o)return"";let b=bal(o);return`<div class="panel detail"><div class="head"><div><small>${o.id}</small><h2>${esc(o.customer)} · ${esc(o.partNumber)}</h2></div>${pill(stat(o))}</div><div class="numbers"><div><small>Requested</small><b>${o.qtyRequested}</b></div><div><small>Shipped</small><b>${o.qtyShipped}</b></div><div class="${b.ship?"warn":""}"><small>Remaining to Ship</small><b>${b.ship}</b></div><div class="${b.invoice?"warn":""}"><small>Remaining to Invoice</small><b>${b.invoice}</b></div></div><div class="detailcols"><div><h3>Workflow</h3>${taskDefinitions.map((t,i)=>`<div class="task"><span>${i<5?"✓":"○"}</span><b>${t[1]}</b><small>${t[2]} → ${t[3]}</small></div>`).join("")}</div><div><h3>Documents</h3><a href="${o.folderLink||"#"}">📁 Open PrePPAP Folder ↗</a><a href="#">▣ Customer PO ↗</a><a href="#">▣ PrePPAP Request ↗</a><a href="#">▣ MES PO → MWS ↗</a><a href="#">▣ MWS Invoice ↗</a><a href="#">▣ MES Invoice ↗</a></div></div>${b.ship?`<div class="alert"><b>⚠ ${b.ship} piece(s) remain.</b> Define compensation / next shipment in PO Balance.</div>`:""}</div>`}
function tasksView(){return`<div class="panel table"><table><thead><tr><th>PrePPAP</th><th>Task</th><th>From</th><th>To</th><th>Due</th><th>Status</th></tr></thead><tbody>${orders.flatMap(o=>taskDefinitions.map((t,i)=>`<tr><td>${o.id}</td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td><td>${o.requiredDate}</td><td>${pill(i<5?"Completed":"In Progress")}</td></tr>`)).join("")}</tbody></table></div>`}
function balances(){return`<div class="panel table"><table><thead><tr><th>PrePPAP</th><th>PO</th><th>Ordered</th><th>Shipped</th><th>Remaining</th><th>Compensation</th></tr></thead><tbody>${orders.map(o=>{let b=bal(o);return`<tr><td>${o.id}</td><td>${o.mesPO}</td><td>${o.mesPOQty}</td><td>${o.qtyShipped}</td><td class="${b.ship?"balance":""}">${b.ship}</td><td>${b.ship?pill("Open Balance"):pill("Completed")}</td></tr>`}).join("")}</tbody></table></div><div class="panel note"><h2>Compensation</h2><p>V1 calculates the remaining quantity. Next iteration: action type, related PO, resolution date and closure evidence.</p></div>`}
function shipments(){return`<div class="panel table"><table><thead><tr><th>PrePPAP</th><th>Method</th><th>Part Number</th><th>Purpose</th><th>Qty</th><th>FedEx</th><th>References</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${o.id}</td><td>${esc(o.shippingMethod)}</td><td>${o.partNumber}</td><td>${o.purpose}</td><td>${o.qtyShipped}</td><td>${esc(o.fedex||"—")}</td><td>${o.shippingMethod==="MWS → Customer"?`${o.partNumber} · ${o.purpose}`:"MES process"}</td></tr>`).join("")}</tbody></table></div>`}
function bind(){document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>{view=x.dataset.nav;render()});document.querySelectorAll("[data-order]").forEach(x=>x.onclick=()=>{selected=x.dataset.order;view="orders";render()});document.querySelector("#q")?.addEventListener("input",populate);document.querySelector("#f")?.addEventListener("change",populate);populate();document.querySelector("#new")?.addEventListener("click",newOrder)}
function newOrder(){let id=`PP-${new Date().getFullYear()}-${String(orders.length+1).padStart(3,"0")}`;orders.unshift({id,customer:"New Customer",partNumber:"New PN",purpose:"Pre-Production",requiredDate:"",qtyRequested:0,mesPO:"",mesPOQty:0,shippingMethod:"Monterrey → Customer",qtyShipped:0,qtyInvoiced:0,folderLink:"#"});saveLocalOrders(orders);selected=id;view="orders";render()}
render();
